# Generated by Django 5.0.3 on 2024-05-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_course_enrollment_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
