# Generated by Django 5.0.3 on 2024-05-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
    ]
